### ISSUE TITLE
FAB Button functionality

### ISSUE THREAD

**Issue by lelui12cr** [eoscostarica/eos-rate#142]
Design the interaction of the feature 'Compare' using the FAB button behavior.

**Comment by gaboesquivel** [comment]
any update @lelui12cr ? this is marked as part of v1, I assume this is for mobile only

**Comment by lelui12cr** [comment]
working with Daniel on this

**Comment by murillojorge** [comment]
How about this for the FAB?

https://zpl.io/VqlzxM6

![Desktop BPs Closed Compare - v1 0](https://user-images.githubusercontent.com/1179619/54655212-ad97f180-4a86-11e9-989a-d6d87d7c4e64.png)

**Comment by arturocr** [comment]
@murillojorge since we are kind of following the material design guidelines, I think we can use the rounded version of the button as stated [here](https://material.io/design/components/buttons-floating-action-button.html#extended-fab). That way the default component library we are using would work out of the box for our purpose. What do you think?

**Comment by murillojorge** [comment]
The FAB toggle visibility for the compare component. At least that was the initial idea. Do you think that it performs the primary, or most common, action on this screen?
https://zpl.io/VqlzxM6
![Desktop BPs Closed Compare - v1 0](https://user-images.githubusercontent.com/1179619/60138311-20d89000-9767-11e9-856f-40cbcbeb7a46.png)
