### ISSUE TITLE
Radar Grid Design

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#234]
We need to show the grid lines within the radar this task is donde with JS code . 
We need to research this task. 

![image](https://user-images.githubusercontent.com/5632966/72397466-97d67580-3705-11ea-903f-63ff21f8874a.png)

**Comment by murillojorge** [comment]
Find the component here:
https://zpl.io/bPvGEL6
Please ignore the category labels. We have the right ones in place now.

**Comment by murillojorge** [comment]
After discussing with @tetogomez about the coloring of the grid. We have come up with the conclusion that we need to be a little flexible with the design for a while, since it appears to be a bug on the actual component, so the coloring will be something more like this:

![Screen Shot 2020-01-23 at 12 01 21](https://user-images.githubusercontent.com/1179619/73010699-8281db00-3dd8-11ea-9971-296331fb9961.png)

I like the fact that we can still see the angle lines that point out the categories, but the value circles are more subtle. **The only thing that's missing here is the value of the points showing on the tooltip**. 

What do you think @xavier506 @edgar-eoscostarica ?
