### ISSUE TITLE
Homepage: Short Description

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#32]
We should prepare a short description on what is EOS Rate and why its important for the community.

This content will be used in the home page and in the github readme.

<img width="407" alt="home-page" src="https://user-images.githubusercontent.com/391270/47598298-42bf1000-d957-11e8-863b-544ba35dc737.png">

**Comment by edgar-eoscostarica** [comment]
##Build Your Vote on EOS Rate

EOSRate is a community-driven visual rating tool that allows EOS token holders to easily rate Block Producers in distinct categories. EOSRate allows users to log in using their preferred EOS wallet and submit a rating compilation from their EOS account onchain.

##One Account. One Rating
Each EOS account can submit their rating for each Block Producer as many times as they like facilitating a "liquid democracy", however, the weighting is independent from the amount the EOS account holds. One account = one submission of equal weight. 

##Our LEAF Visualizer
Our unique radar component we call the "LEAF" (Liquid EOS Attribute Factors) allows users to quickly compared different block producers and "build" their 30 BP vote by filling in as much of the LEAF as possible to facilitate the most diverse group for the network. The LEAF also allows voters to compare different proxies by visualizing each of the underlying BP "leafs" the proxy represents.

##Community Driven Rating System 
We are aware that there are many great rating sites for BPs currently in the ecosystem and we incorporate their contributions by including links to theses resources. EOSRate, however, focuses on "wisdom of crowds" and rather than using one person's rating we allow the community to build upon the ratings of others. This process can identify outliers and self-correct by increasing the submissions. We do not influence the account of the ratings, just present the facts in a visually appealing format. 

##How it Works
To use EOS rate, please follow the steps below:

1. If your would like to submit your rating, sign in with your preferred EOS Wallet (Scatter/Lynx/Meet.One/TokenPoken/Etc). No need to sign in just to view the each LEAF.
2. Search or filter through the list of BPs
3. Select the BP you wish to rate
4. Move the slider from 1-10 for each catergory under the BP. For example, "1" for a TestNet category would indicate poor performance in testnets or lack of involvement and vice versa. 
5. When you are done selecting a rating for each slider under each BP, review your ratings under the "Submit Ratings" cart.
6. Confirm your submissions and review the command function.
7. If correct, confirm the transaction and your are done!
8. Feel free to return and update your rating at any time.

**Comment by gaboesquivel** [comment]
thanks @edgar-eoscostarica 

@mahcr @murillojorge use this on the home page, feel free to make modifications to fit the design's spacing. We will review again together once it's ready. 

rel #57
