### ISSUE TITLE
Some BPs show they have no bp.json when they actually do

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eos-rate#429]
![image](https://user-images.githubusercontent.com/5632966/82368648-02a8fd80-99d3-11ea-90db-df0af94ee7ff.png)

https://www.eosargentina.io/bp.json

@kuronosec  this is loaded in `sync-bps.js` it it executing correctly?

**Comment by xavier506** [comment]
Should we store the logo images on our backend server to avoid timeouts while loading the page?

**Comment by kuronosec** [comment]
@xavier506 the fix you made to avoid overwriting empty bp.json helps here. I tested the old eosrate server and the connection errors I see are different to the new server in kubernetes. I will investigate what causes that problem.

**Comment by kuronosec** [comment]
So this was an interesting bug! Thanks to this comment: https://www.reddit.com/r/linuxadmin/comments/bjg53u/how_did_my_server_end_up_resolving_all_internal/ I realized that one of the dns servers we were using (4.2.2.1) was randomly returning crazy addresses (akama's ones) for some urls we wanted to download the bp.json from. I removed such nameserver from our infra and the problem is gone!
