### ISSUE TITLE
Analyze moving all node_modules directories inside containers

### ISSUE THREAD

**Issue by kuronosec** [eoscostarica/eos-rate#455]
@xavier506, @danazkari at the moment we have a frontend container with the node dependencies compiled inside the container, while for the hapi container we mount a nfs directory with the source and dependencies. Should we make both consistent, and put everything inside the container, even if they get bigger? I don't actually know whats the best practice, but compiling all inside the containers sounds more consistent and easy to update. What do you think?

**Comment by kuronosec** [comment]
The same for demux, but I am wondering if we really need demux in production.

**Comment by danazkari** [comment]
Well @kuronosec, the best practice for docker images is to keep them as light as possible, in fact if you analyze the front-end docker file, it has different stages, and the image layers we keep, are just the last ones in the process, which only contain the built js/html/css files.

In this case, there's not much gain if we keep some kind of consistency, just because they both use JS, it doesn't mean they behave the same 😋

I hope it makes sense

**Comment by kuronosec** [comment]
Thanks @danazkari for the info, it totally makes sense :) I'll look for a cleaner way to apply changes to hapi in the nfs server then.
