### ISSUE TITLE
Homepage Video

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/eos-rate#62]
We need to record a 2 minute video for the homepage about EOS Rate. 

The goals of the video are:

- explain what it is and it's objectives.
- describe how it works.
- let people know how to get involved in the project.

**Comment by xavier506** [comment]
@edgar-eoscostarica  whats the status of this task?

**Comment by murillojorge** [comment]
Mi proposal is to create a Q&A. 3 questions and an invite to interact with us.
Edgar can touch each topic separately and upload to the Zoom cloud, and I'll be happy to edit the result.

### Q&A

**What is EOSRate?**

LEAF Graphs - Quick explanation about the concept and how visual elements read easier.
Categories:
* Transparency
    *  communication
    * ownership disclosure
    * financial disclosure
* Trustiness:
    * quality of being loyal or reliable
    * follows statements on the regproducer contract
    * doesn't get involve in dishonest behavior
    * coherence to their public block producer pledge
* Community:
    * user education
    * developer education
    * support
    * engagement
    * podcasts, blogs, video
    * meetups, hackathons and events
* Development:
    * open source software
    * contributions to eosio software
    * contributions to governance model
    * add value dapps and services, wallets
* Infrastructure:
    * mainnet resources
    * second layer services ( explorers, apis, etc )
    * testnets
    * downtime
    * security
    * apis

BP Listing - BPs should comply with the regproducer contract in order to be listed. 
Quantitative data help raters understand BPs actual situation on the eos network
Compare tool - Comparing it's a great way to modulate your rates. 

**How do the rating process occur?**
Scatter identity is linked to real eos users and their wallets.
On-block, immutable and transparent.
Optional categories gives the opportunity to rate only what you know about.
Degrading votes will provide up to date information.
Spam prevention is absolutely important in order to provide factual information.

**Why are ratings important?**
Democracy need tools in order to work properly.
Communication - all eos users even the smallest ones, need an output to share their experiences with BPs.
Bad actors need to be exposed for their actions against the established rules on the constitution. Vote buying?
Good actors need to be rewarded for their work.

**Invitation to interact**
EOSCostaRica
Telegram
Github
EOS-Surf ?

**Comment by JulianAlvarado** [comment]
Let's dicuss it on today's call

**Comment by ldrojas** [comment]
Script para el video.

[20190825 EOS Rate homepage video script.docx](https://github.com/eoscostarica/eos-rate/files/3538525/20190825.EOS.Rate.homepage.video.script.docx)

**Comment by JulianAlvarado** [comment]
@ldrojas tenemos algun progreso del video para publicarlo?

**Comment by xavier506** [comment]
@ldrojas 

Can we get an uodate on this task or a  copy of the first version of this video ? 

Perhaps we can upload it to eoscr's youtube channel and then emben in eos rate frkom there?

**Comment by xavier506** [comment]
@tetogomez 

https://youtu.be/bo9ksd_X8fM

**Comment by JulianAlvarado** [comment]
@ldrojas hay que actualizar el contenido del video cuando se haga el cambio de schema de colores del diseño

**Comment by murillojorge** [comment]
We should explore leaving the audio and record the screen while using the app.

**Comment by xavier506** [comment]
@ldrojas We have a new color scheme for eos rate published so I think this is a really good time to replace the screen shots in the hompgae video. 

Is that something we can easily do?

**Comment by murillojorge** [comment]
Please take a look at the coloring and other visual aspects with @roafroaf . Thanks.
